Q1. Pandas version
Explanation:
First, we import Pandas and use pd.__version__ to check which version is installed in the Jupyter environment.

In [2]:
# Q1: Pandas version

import pandas as pd

# Display the installed Pandas version
print("Pandas version:", pd.__version__)


Pandas version: 3.0.6


Answer: The version displayed by your notebook is your answer to Q1.

Q2. Records count
Explanation:
We first load the CSV dataset using pd.read_csv(). Then, len(df) gives us the number of records (rows) in the dataset.

In [3]:
# Q2: Records count

# URL of the Car Fuel Efficiency dataset
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

# Read the dataset into a Pandas DataFrame
df = pd.read_csv(url)

# Count the number of records
record_count = len(df)

print("Number of records:", record_count)


Number of records: 10000


Q3. Fuel types
Explanation:
We use the nunique() method to count the number of unique values in the fuel_type column.

In [4]:
# Q3: Number of fuel types

# Count the unique fuel types
fuel_type_count = df["fuel_type"].nunique()

print("Number of fuel types:", fuel_type_count)

# Display the actual fuel types for verification
print("Fuel types:", df["fuel_type"].unique())


Number of fuel types: 3
Fuel types: <StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str


Q4. Missing values
Explanation:
First, we calculate the number of missing values in every column using isna().sum().
Then, isna().any() identifies which columns contain at least one missing value. Finally, we count those columns.

In [5]:
# Q4: Number of columns with missing values

# Count missing values in each column
missing_values = df.isna().sum()

print("Missing values in each column:")
print(missing_values)

# Count how many columns contain at least one missing value
columns_with_missing = df.isna().any().sum()

print("\nNumber of columns with missing values:", columns_with_missing)


Missing values in each column:
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Number of columns with missing values: 2


Q5. Maximum fuel efficiency of cars from Asia
Explanation:
We first filter the dataset to keep only cars whose origin is "Asia".
Then we use max() on the fuel-efficiency column to find the highest value.

In [6]:
# Q5: Maximum fuel efficiency of cars from Asia

# Select only cars manufactured in Asia
asia_cars = df[df["origin"] == "Asia"]

# Find the maximum fuel efficiency
max_efficiency = asia_cars["fuel_efficiency_mpg"].max()

print("Maximum fuel efficiency for cars from Asia:", max_efficiency)


Maximum fuel efficiency for cars from Asia: 41.2


Q6. Median value of horsepower
Explanation:
First, we calculate the median of the horsepower column.
Then, we find the most frequent horsepower value using mode().

Next, we use fillna() to replace missing horsepower values with this most frequent value.

Finally, we calculate the median again and compare it with the original median.



In [7]:
# Q6: Median horsepower before and after filling missing values

# Calculate the median horsepower before filling missing values
median_before = df["horsepower"].median()

# Find the most frequent horsepower value
most_frequent_horsepower = df["horsepower"].mode()[0]

# Fill missing horsepower values with the most frequent value
df["horsepower"] = df["horsepower"].fillna(most_frequent_horsepower)

# Calculate the median horsepower after filling missing values
median_after = df["horsepower"].median()

print("Median horsepower before filling missing values:", median_before)
print("Most frequent horsepower:", most_frequent_horsepower)
print("Median horsepower after filling missing values:", median_after)

# Compare the two median values
if median_after > median_before:
    print("\nAnswer: Yes, it increased")
elif median_after < median_before:
    print("\nAnswer: Yes, it decreased")
else:
    print("\nAnswer: No, it did not change")


Median horsepower before filling missing values: 254.0
Most frequent horsepower: 252.0
Median horsepower after filling missing values: 252.0

Answer: Yes, it decreased


Q7. Sum of weights
Explanation:
For this question, we:

Select cars from Asia.

Select vehicle_weight and model_year.

Take the first 7 records.

Convert the result to a NumPy array X.

Calculate 
X
T
X
.

Calculate its inverse.

Create the y array given in the question.

Calculate the linear regression weights:

w
=
(
X
T
X
)
−
1
X
T
y

Finally, calculate the sum of all elements of w.



In [8]:
# Q7: Linear regression and sum of weights

import numpy as np

# Select all cars from Asia
asia_cars = df[df["origin"] == "Asia"]

# Select vehicle_weight and model_year
# Then select the first 7 rows
X = asia_cars[["vehicle_weight", "model_year"]].head(7).to_numpy()

print("X:")
print(X)

# Calculate X transpose multiplied by X
XTX = X.T @ X

print("\nXTX:")
print(XTX)

# Calculate the inverse of XTX
XTX_inv = np.linalg.inv(XTX)

print("\nInverse of XTX:")
print(XTX_inv)

# Create the y array provided in the homework
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Calculate the weights:
# w = (XTX)^(-1) * X^T * y
w = XTX_inv @ X.T @ y

print("\nWeights (w):")
print(w)

# Calculate the sum of all elements in w
sum_of_weights = w.sum()

print("\nSum of weights:", sum_of_weights)


X:
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

XTX:
[[131950500  60750580]
 [ 60750580  28041424]]

Inverse of XTX:
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

Weights (w):
[0.13644777 0.2327492 ]

Sum of weights: 0.36919696904925203
